### ISSUE TITLE
Expired SSL certificate on `files.nomad.menu`

### ISSUE THREAD

**Issue by Qapf** [jamf/DEPNotify#1]
Heya!

The latest release, [1.1.6](https://github.com/jamf/DEPNotify/releases/tag/1.1.6) is hosted on `files.nomad.menu`

> Application Zip file: https://files.nomad.menu/DEPNotify.zip
> Package installer: https://files.nomad.menu/DEPNotify.pkg

The SSL certificate for `files.nomad.menu` appears to have expired on `Mon, 13 Nov 2023 23:59:59 GMT`

Would it be possible to investigate the hosting and update the certificate on the site hosting DEPnotify please?

**Comment by macshome** [comment]
We've renewed the certificates and this should be fixed now.
